networks:
  confluence-network:
    external: true
  traefik-network:
    external: true

volumes:
  confluence-data:
  confluence-postgres:
  confluence-postgres-backup:
  confluence-data-backups:
  confluence-database-backups:
  traefik-certificates:

services:
  postgres:
    image: ${CONFLUENCE_POSTGRES_IMAGE_TAG}
    volumes:
      - confluence-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${CONFLUENCE_DB_NAME}
      POSTGRES_USER: ${CONFLUENCE_DB_USER}
      POSTGRES_PASSWORD: ${CONFLUENCE_DB_PASSWORD}
    networks:
      - confluence-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${CONFLUENCE_DB_NAME}", "-U", "${CONFLUENCE_DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  confluence:
    image: ${CONFLUENCE_IMAGE_TAG}
    volumes:
      - confluence-data:${DATA_PATH}
    environment:
      JVM_MINIMUM_MEMORY: ${CONFLUENCE_JVM_MINIMUM_MEMORY}
      JVM_MAXIMUM_MEMORY: ${CONFLUENCE_JVM_MAXIMUM_MEMORY}
      ATL_PROXY_NAME: ${CONFLUENCE_HOSTNAME}
      ATL_TOMCAT_SECURE: 'true'
      ATL_TOMCAT_SCHEME: https
      ATL_PROXY_PORT: 443
      ATL_DB_TYPE: postgresql
      ATL_DB_DRIVER: org.postgresql.Driver
      ATL_JDBC_USER: ${CONFLUENCE_DB_USER}
      ATL_JDBC_PASSWORD: ${CONFLUENCE_DB_PASSWORD}
      ATL_JDBC_URL: jdbc:postgresql://postgres:5432/${CONFLUENCE_DB_NAME}
    networks:
      - confluence-network
      - traefik-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    labels:
      # Enable Traefik for this container
      - "traefik.enable=true"
      # Match incoming requests on a specific hostname
      - "traefik.http.routers.confluence.rule=Host(`${CONFLUENCE_HOSTNAME}`)"
      # Assign the router to a named Traefik service
      - "traefik.http.routers.confluence.service=confluence"
      # Use the 'websecure' (HTTPS) entry point
      - "traefik.http.routers.confluence.entrypoints=websecure"
      # Define the internal container port for routing
      - "traefik.http.services.confluence.loadbalancer.server.port=8090"
      # Enable TLS on this router
      - "traefik.http.routers.confluence.tls=true"
      # Use Let's Encrypt for certificate management
      - "traefik.http.routers.confluence.tls.certresolver=letsencrypt"
      # Pass the original Host header to the container
      - "traefik.http.services.confluence.loadbalancer.passhostheader=true"
      # Apply a compression middleware
      - "traefik.http.routers.confluence.middlewares=compresstraefik"
      # Define settings for the compression middleware
      - "traefik.http.middlewares.compresstraefik.compress=true"
      # Define TCP router rules for Confluence Synchrony to match all incoming requests (HostSNI)
      - "traefik.tcp.routers.confluence-synchrony.rule=HostSNI(`*`)"
      # Assign the Confluence Synchrony router to a named Traefik service
      - "traefik.tcp.routers.confluence-synchrony.service=confluence-synchrony"
      # Use the 'Confluence Synchrony' (custom) entry point
      - "traefik.tcp.routers.confluence-synchrony.entrypoints=confluence-synchrony"
      # Define the internal container port for routing to the Confluence Synchrony service
      - "traefik.tcp.services.confluence-synchrony.loadbalancer.server.port=11434"
      # Specify which Docker network Traefik should use for routing
      - "traefik.docker.network=traefik-network"

    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      traefik:
        condition: service_healthy

  traefik:
    image: ${TRAEFIK_IMAGE_TAG}
    command:
      # Set the log level (DEBUG, INFO, WARN, ERROR)
      - "--log.level=${TRAEFIK_LOG_LEVEL}"
      # Enable the built-in API and web-based dashboard on /dashboard
      - "--api.dashboard=true"
      # Enable the /ping endpoint so we can health-check Traefik
      - "--ping=true"
      # Assign the /ping endpoint to a dedicated entry point on port 8082
      - "--ping.entrypoint=ping"
      - "--entrypoints.ping.address=:8082"
      # Define the primary HTTP entry point on port 80
      - "--entrypoints.web.address=:80"
      # Define the secure (HTTPS) entry point on port 443
      - "--entrypoints.websecure.address=:443"
      # Define the Synchrony entry point on port 8091
      - "--entryPoints.synchrony.address=:8091"
      # Enable the Docker provider to detect containers and their labels
      - "--providers.docker=true"
      # Point Traefik to the Docker socket
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      # Prevent automatic exposure of all containers; only expose containers
      # with "traefik.enable=true"
      - "--providers.docker.exposedbydefault=false"
      # Use ACME (Let's Encrypt) to generate/renew certificates via TLS challenge
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      # The email address used by Let's Encrypt for renewal notices
      - "--certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL}"
      # The file where ACME certificates are stored inside the container
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme.json"
      # Enable Prometheus metrics
      - "--metrics.prometheus=true"
      # Configure Prometheus histogram buckets
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      # Check for newer Traefik versions and optionally log that info
      - "--global.checknewversion=true"
      # Disable sending anonymous usage data to the Traefik maintainers
      - "--global.sendanonymoususage=false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certificates:/etc/traefik/acme
    networks:
      - traefik-network
    ports:
      - "80:80"
      - "443:443"
      - "8091:8091"
    healthcheck:
      test: ["CMD", "wget", "http://localhost:8082/ping","--spider"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    labels:
      # Enable Traefik for this container.
      - "traefik.enable=true"
      # A router to expose the Traefik dashboard
      - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_HOSTNAME}`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.service=api@internal"
      # asic Authentication for the Traefik dashboard
      - "traefik.http.routers.dashboard.middlewares=authtraefik"
      - "traefik.http.middlewares.authtraefik.basicauth.users=${TRAEFIK_BASIC_AUTH}"
      # Specify the internal server port to the dashboard service
      - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
      # Pass the original Host header to the backend
      - "traefik.http.services.dashboard.loadbalancer.passhostheader=true"
      # HTTP -> HTTPS redirect for all hosts
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    restart: unless-stopped

  backups:
    image: ${CONFLUENCE_POSTGRES_IMAGE_TAG}
    command: >-
      sh -c 'sleep $BACKUP_INIT_SLEEP &&
      while true; do
        pg_dump -h postgres -p 5432 -d $CONFLUENCE_DB_NAME -U $CONFLUENCE_DB_USER | gzip > $POSTGRES_BACKUPS_PATH/$POSTGRES_BACKUP_NAME-$(date "+%Y-%m-%d_%H-%M").gz &&
        tar -zcpf $DATA_BACKUPS_PATH/$DATA_BACKUP_NAME-$(date "+%Y-%m-%d_%H-%M").tar.gz $DATA_PATH &&
        find $POSTGRES_BACKUPS_PATH -type f -mtime +$POSTGRES_BACKUP_PRUNE_DAYS | xargs rm -f &&
        find $DATA_BACKUPS_PATH -type f -mtime +$DATA_BACKUP_PRUNE_DAYS | xargs rm -f;
        sleep $BACKUP_INTERVAL; done'
    volumes:
      - confluence-postgres-backup:/var/lib/postgresql/data
      - confluence-data:${DATA_PATH}
      - confluence-data-backups:${DATA_BACKUPS_PATH}
      - confluence-database-backups:${POSTGRES_BACKUPS_PATH}
    environment:
      CONFLUENCE_DB_NAME: ${CONFLUENCE_DB_NAME}
      CONFLUENCE_DB_USER: ${CONFLUENCE_DB_USER}
      PGPASSWORD: ${CONFLUENCE_DB_PASSWORD}
      BACKUP_INIT_SLEEP: ${BACKUP_INIT_SLEEP}
      BACKUP_INTERVAL: ${BACKUP_INTERVAL}
      POSTGRES_BACKUP_PRUNE_DAYS: ${POSTGRES_BACKUP_PRUNE_DAYS}
      DATA_BACKUP_PRUNE_DAYS: ${DATA_BACKUP_PRUNE_DAYS}
      POSTGRES_BACKUPS_PATH: ${POSTGRES_BACKUPS_PATH}
      DATA_BACKUPS_PATH: ${DATA_BACKUPS_PATH}
      DATA_PATH: ${DATA_PATH}
      POSTGRES_BACKUP_NAME: ${POSTGRES_BACKUP_NAME}
      DATA_BACKUP_NAME: ${DATA_BACKUP_NAME}
    networks:
      - confluence-network
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
